### ISSUE TITLE
Add a pip requirements file

### ISSUE THREAD

**Issue by skrzepto** [tutoraweb/Kiosk#7]
This will install all the dependencies for us so we don't need to hunt them down

**Comment by sdimitro** [comment]
Assigning it to you by default. If you don't feel like doing it, I can take it.

**Comment by sdimitro** [comment]
by the way you need to accept my team invitation

**Comment by skrzepto** [comment]
accepted and its done

commit: 91cbfa3f28742916a85b0c59b4ee8170dcec0816

**Comment by sdimitro** [comment]
ok I can take it from here, THe issue number is #7 btw ;P

**Comment by sdimitro** [comment]
Closed! Thank you Simon.
